/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructuras.Lista;
import Estructuras.Matriz;
import Graphviz.Graphviz_Lista;

/**
 *
 * @author Denis
 */
public class Editor_Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Editor_Tablero
     */
    Matriz Tablero;
    Lista Objetos;
    public Editor_Tablero() {
        initComponents();
    }

    Editor_Tablero(Lista Objetos) {
        initComponents();
        Tablero = new Matriz();
        this.Objetos = Objetos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCol = new javax.swing.JButton();
        AddFil = new javax.swing.JButton();
        BtGraficar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        BtDatos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AddCol.setText("Agregar Columna");
        AddCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddColActionPerformed(evt);
            }
        });
        getContentPane().add(AddCol);
        AddCol.setBounds(490, 10, 115, 23);

        AddFil.setText("Agregar Fila");
        AddFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFilActionPerformed(evt);
            }
        });
        getContentPane().add(AddFil);
        AddFil.setBounds(610, 10, 115, 23);

        BtGraficar.setText("Graficar");
        BtGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(BtGraficar);
        BtGraficar.setBounds(10, 11, 71, 23);

        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtEliminar);
        BtEliminar.setBounds(87, 11, 69, 23);

        BtDatos.setText("Datos");
        BtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDatosActionPerformed(evt);
            }
        });
        getContentPane().add(BtDatos);
        BtDatos.setBounds(162, 11, 61, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 710, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddColActionPerformed
        Tablero.Incerdar_Columna();
    }//GEN-LAST:event_AddColActionPerformed

    private void AddFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFilActionPerformed
        Tablero.Incertar_Fila();
    }//GEN-LAST:event_AddFilActionPerformed

    private void BtGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGraficarActionPerformed
        Graphviz_Lista a = new Graphviz_Lista(Objetos);
        
    }//GEN-LAST:event_BtGraficarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void BtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCol;
    private javax.swing.JButton AddFil;
    private javax.swing.JButton BtDatos;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtGraficar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
