/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructuras.*;
import Graphviz.Graphviz;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author Denis
 */
public class Editor_Tablero extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Editor_Tablero
     */
    Matriz Tablero;
    Lista Objetos;
    Nodo_Matriz Puntero;
    int X = 0, Y = 0;//24,12
    int corrimiento = 0;

    public Editor_Tablero() {
        initComponents();
    }

    Editor_Tablero(Lista Objetos) {
        initComponents();
        Tablero = new Matriz();
        this.Objetos = Objetos;
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCol = new javax.swing.JButton();
        AddFil = new javax.swing.JButton();
        BtGraficar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        BtDatos = new javax.swing.JButton();
        Area = new javax.swing.JPanel();
        LeftBt = new javax.swing.JButton();
        RightBt = new javax.swing.JButton();
        BtSelect = new javax.swing.JToggleButton();
        BtSiguiente = new javax.swing.JButton();
        BtQuitar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 490));
        getContentPane().setLayout(null);

        AddCol.setText("Agregar Columna");
        AddCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddColActionPerformed(evt);
            }
        });
        getContentPane().add(AddCol);
        AddCol.setBounds(490, 10, 115, 23);

        AddFil.setText("Agregar Fila");
        AddFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFilActionPerformed(evt);
            }
        });
        getContentPane().add(AddFil);
        AddFil.setBounds(610, 10, 115, 23);

        BtGraficar.setText("Graficar");
        BtGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(BtGraficar);
        BtGraficar.setBounds(10, 11, 90, 23);

        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtEliminar);
        BtEliminar.setBounds(100, 10, 90, 23);

        BtDatos.setText("Datos");
        BtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDatosActionPerformed(evt);
            }
        });
        getContentPane().add(BtDatos);
        BtDatos.setBounds(190, 10, 100, 23);

        Area.setMinimumSize(new java.awt.Dimension(720, 360));
        Area.setPreferredSize(new java.awt.Dimension(720, 360));

        javax.swing.GroupLayout AreaLayout = new javax.swing.GroupLayout(Area);
        Area.setLayout(AreaLayout);
        AreaLayout.setHorizontalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        AreaLayout.setVerticalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(Area);
        Area.setBounds(10, 40, 720, 360);

        LeftBt.setText(">");
        LeftBt.setEnabled(false);
        LeftBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftBtActionPerformed(evt);
            }
        });
        getContentPane().add(LeftBt);
        LeftBt.setBounds(690, 420, 41, 23);

        RightBt.setText("<");
        RightBt.setEnabled(false);
        RightBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightBtActionPerformed(evt);
            }
        });
        getContentPane().add(RightBt);
        RightBt.setBounds(10, 420, 41, 23);

        BtSelect.setMaximumSize(new java.awt.Dimension(70, 70));
        BtSelect.setMinimumSize(new java.awt.Dimension(30, 30));
        BtSelect.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(BtSelect);
        BtSelect.setBounds(360, 410, 40, 40);

        BtSiguiente.setText("Siguiente");
        BtSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(BtSiguiente);
        BtSiguiente.setBounds(510, 420, 110, 23);

        BtQuitar.setText("Quitar");
        getContentPane().add(BtQuitar);
        BtQuitar.setBounds(170, 420, 63, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddColActionPerformed
        Tablero.Incerdar_Columna();
        X++;
        Pintar();
        if (X > 24) {
            AjustarBotones();
        }
    }//GEN-LAST:event_AddColActionPerformed

    private void AddFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFilActionPerformed
        if (Tablero.Raiz == null) {
            X++;
        }
        Tablero.Incertar_Fila();
        Y++;
        Pintar();
    }//GEN-LAST:event_AddFilActionPerformed

    private void BtGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGraficarActionPerformed
        Graphviz a = new Graphviz(Objetos);
        a = new Graphviz(Tablero);
    }//GEN-LAST:event_BtGraficarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
        Eliminar Ventana2 = new Eliminar(Tablero);
        Ventana2.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                Puntero = Tablero.Raiz;
                ActualizarPos();
                Pintar();
            }

            @Override
            public void windowClosing(WindowEvent e) {

                Puntero = Tablero.Raiz;
                ActualizarPos();
                Pintar();
            }

        });
        Ventana2.setVisible(true);
        //Ventana.setVisible(true);
        //while(Ventana.isVisible()){}
        //System.out.println("Adios");
        //if(Ventana){}
        //Dialog g = new Dialoge(this, Ventana);
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void BtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDatosActionPerformed
        Datos Ventana = new Datos(Tablero.Raiz);
        Ventana.setVisible(true);
    }//GEN-LAST:event_BtDatosActionPerformed

    private void LeftBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftBtActionPerformed
        // TODO add your handling code here:
        corrimiento--;
        Puntero = Puntero.derecha;
        MoverDer();
        AjustarBotones();
    }//GEN-LAST:event_LeftBtActionPerformed

    private void RightBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightBtActionPerformed
        corrimiento++;
        Puntero = Puntero.izquierda;
        MoverIzq();
        AjustarBotones();
    }//GEN-LAST:event_RightBtActionPerformed

    private void BtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSiguienteActionPerformed
        Tablero Tablero = new Tablero(this.Tablero);
        Tablero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCol;
    private javax.swing.JButton AddFil;
    private javax.swing.JPanel Area;
    private javax.swing.JButton BtDatos;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtGraficar;
    private javax.swing.JToggleButton BtQuitar;
    private javax.swing.JToggleButton BtSelect;
    private javax.swing.JButton BtSiguiente;
    private javax.swing.JButton LeftBt;
    private javax.swing.JButton RightBt;
    // End of variables declaration//GEN-END:variables

    private void Pintar() {
        if (Puntero == null && Tablero.Raiz != null) {
            Puntero = Tablero.Raiz;
        }
        if (Puntero != null) {
            //System.out.println("Hola");
            Nodo_Matriz Aux1 = Puntero;
            while (Aux1 != null) {
                //System.out.println("Aux1");
                Nodo_Matriz Aux2 = Aux1;
                while (Aux2 != null) {
                    //System.out.println("Aux2");
                    if (!Aux2.isVisible()) {
                        //System.out.println("No es visible");
                        Area.add(Aux2);
                        Aux2.setVisible(true);
                        Aux2.setBounds((Aux2.X + corrimiento) * 30, Aux2.Y * 30, 30, 30);
                        //aux.setText("Hola");
                        Aux2.setBorder(LineBorder.createGrayLineBorder());
                        Aux2.setOpaque(true);
                        Aux2.addMouseListener(this);
                        //System.out.println(Color.);
                        //float a = 0.6;
                        Aux2.setBackground(Color.getHSBColor(0.63f, 0.45f, 1.0f));
                        //Area.revalidate();
                        //Area.repaint();
                    }
                    Aux2 = Aux2.derecha;
                }
                Aux1 = Aux1.abajo;
            }
        }
    }

    private void Cargar() {
        if (Objetos.Raiz != null) {
            BtSelect.setIcon(new ImageIcon(Objetos.Raiz.ruta));
        } else {
            BtSelect.setIcon(null);
            BtSelect.setEnabled(false);
        }
        BtSelect.setSelected(false);
    }

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if (BtSelect.isSelected()) {
            //System.out.println("Hola");
            //System.out.println(e.getSource());
            Nodo_Matriz Aux = (Nodo_Matriz) e.getComponent();
            if (Aux.Objeto == null) {
                Aux.Objeto = Objetos.Extraer_FIFO();
                Aux.setIcon(BtSelect.getIcon());
                Cargar();
            }
        }
    }

    private void AjustarBotones() {
        if (Puntero.izquierda != null) {
            RightBt.setEnabled(true);
        } else {
            RightBt.setEnabled(false);
        }
        int Aux1 = 0;
        Nodo_Matriz Aux2 = Puntero;
        while (Aux1 < 24 && Aux2 != null) {
            Aux2 = Aux2.derecha;
            Aux1++;
        }
        if (Aux2 != null) {
            LeftBt.setEnabled(true);
        } else {
            LeftBt.setEnabled(false);
        }
    }

    private void MoverDer() {
        Nodo_Matriz Aux1 = Tablero.Raiz;
        while (Aux1 != null) {
            Nodo_Matriz Aux2 = Aux1;
            while (Aux2 != null) {
                Rectangle info = Aux2.getBounds();
                Aux2.setBounds(info.x - 30, info.y, 30, 30);
                Aux2 = Aux2.derecha;
            }
            Aux1 = Aux1.abajo;
        }
    }

    private void MoverIzq() {
        Nodo_Matriz Aux1 = Tablero.Raiz;
        while (Aux1 != null) {
            Nodo_Matriz Aux2 = Aux1;
            while (Aux2 != null) {
                Rectangle info = Aux2.getBounds();
                Aux2.setBounds(info.x + 30, info.y, 30, 30);
                Aux2 = Aux2.derecha;
            }
            Aux1 = Aux1.abajo;
        }
    }
    private void ActualizarPos(){
        Nodo_Matriz Aux1 = Tablero.Raiz;
        int y = 0;
        while(Aux1!=null){
            Nodo_Matriz Aux2=Aux1;
            int x =0;
            while(Aux2!=null){
                Aux2.X = x;
                Aux2.Y = y;
                Aux2.setBounds(x*30, y*30, 30, 30);
                //System.out.println("x:" + (x*30) + " y:" + (y*30));
                x++;
                Aux2 = Aux2.derecha;
            }
            y++;
            Aux1 = Aux1.abajo;
        }
    }
}
